title: "Юрий Гагарин - Урегулирование Споров и Медиация"
logo: /assets/img/logo.jpg
theme: jekyll-theme-minimal
description: "Профессиональные услуги медиации и разрешения споров."
show_downloads: false
github:
  is_project_page: false