title: "Юрий Гагарин - Урегулирование Споров и Медиация"
theme: jekyll-theme-minimal
description: "Профессиональные услуги медиации и разрешения споров."
author:
  name: "Юрий Гагарин"
  email: yuri.gagarin@example.com
show_downloads: false